meta_product_name: "AutoTest"
meta_title: "AutoTest - Grade Exams Instantly"
meta_description: "AutoTest allows you to grade scanned hand-written exams in a matter of minutes. Try it out!"
meta_image: "og_autotest.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
